#include "mainwindow.h"
#include "ui_mainwindow.h"

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::paintEvent(QPaintEvent *event) {
    paintAll();
}

void MainWindow::paintAll(QSvgGenerator *generator /* = 0 */) {

    QPainter painter;
    painter.begin(this);

    painter.setFont(QFont("Times", 14, QFont::Bold));
    painter.drawText(QPoint(20, 30), "Testing");

    painter.drawLine(QPoint(50, 60), QPoint(100, 100));

    painter.setBrush(Qt::BDiagPattern);
    painter.drawRect(QRect(40, 120, 80, 30));

    QPen ellipsePen;
    ellipsePen.setColor(Qt::red);
    ellipsePen.setStyle(Qt::DashDotLine);
    painter.setPen(ellipsePen);
    painter.drawEllipse(QPoint(80, 200), 50, 20);

    QPainterPath rectPath;
    rectPath.addRect(QRect(150, 20, 100, 50));
    //这个QPen的构造函数参数意义为：画笔颜色，画笔粗细，画笔样式（虚线），画笔末端样式（默认矩形末端），画笔连接处样式（原角度链接，也有弧形链接）
    painter.setPen(QPen(Qt::red, 1, Qt::DashDotLine, Qt::FlatCap, Qt::MiterJoin));
    painter.setBrush(Qt::yellow);
    painter.drawPath(rectPath);

    QPainterPath ellipsePath;
    ellipsePath.addEllipse(QPoint(200, 120), 50, 20);
    painter.setPen(QPen(QColor(79, 106, 25), 5, Qt::SolidLine, Qt::FlatCap, Qt::MiterJoin));
    painter.setBrush(QColor(122, 163, 39));
    painter.drawPath(ellipsePath);

    QImage image;
    image.load(":/image/test.jpg");
    painter.drawImage(QPoint(200, 150), image);
    painter.end();
}

void MainWindow::on_actionSave_as_SVG_triggered()
{
    //QMessageBox::information(NULL, tr("Open"), tr("Open a file"));
        QString filePath = QFileDialog::getSaveFileName(this, "Save as SVG", "", "SVG files (*.svg)");
        if (filePath=="")
        {
            return;
        }

        QSvgGenerator generator;

        /*generator.setFileName(filePath);
        generator.setSize(QSize(this->width(), this->height()));
        generator.setViewBox(QRect(0, 0, this->width(), this->height()));
        generator.setTitle("SVG example");
        generator.setDescription("This SVG file is generated by Qt.");*/

        //paintAll(generator);
}
